lyrics = (
    "Liar\n"
    "Liar\n"
    "Banana banana banana terracotta\n"
    "Banana terracotta terracotta pie\n"
    "Banana banana banana terracotta\n"
    "Banana terracotta terracotta pie\n"
    "Is there a perfect way of holding you baby?\n"
    "Vicinity of obscenity in your eyes\n"
    "Terracotta terracotta terracotta pie\n"
    "Is there a perfect way of holding you baby?\n"
    "Vicinity of obscenity in your eyes\n"
    "Terracotta pie, hey\n"
    "Terracotta pie, hey\n"
    "Terracotta pie, hey\n"
    "Terracotta pie\n"
    "Banana banana banana banana terracotta\n"
    "Banana terracotta terracotta pie\n"
    "Banana banana banana banana terracotta\n"
    "Banana terracotta terracotta pie\n"
)
